// Code generated by "stringer -type=OpCode"; DO NOT EDIT.

package bytecode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OP_CONSTANT-0]
	_ = x[OP_TRUE-1]
	_ = x[OP_FALSE-2]
	_ = x[OP_NIL-3]
	_ = x[OP_CONSTANT_M1-4]
	_ = x[OP_CONSTANT_0-5]
	_ = x[OP_CONSTANT_1-6]
	_ = x[OP_CONSTANT_2-7]
	_ = x[OP_CONSTANT_3-8]
	_ = x[OP_CONSTANT_4-9]
	_ = x[OP_CONSTANT_5-10]
	_ = x[OP_NEGATE-11]
	_ = x[OP_NOT-12]
	_ = x[OP_ADD-13]
	_ = x[OP_SUBTRACT-14]
	_ = x[OP_MULTIPLY-15]
	_ = x[OP_DIVIDE-16]
	_ = x[OP_EQUAL-17]
	_ = x[OP_NOT_EQUAL-18]
	_ = x[OP_GREATER-19]
	_ = x[OP_LESS-20]
	_ = x[OP_GREATER_EQUAL-21]
	_ = x[OP_LESS_EQUAL-22]
	_ = x[OP_DEFINE_GLOBAL-23]
	_ = x[OP_GET_GLOBAL-24]
	_ = x[OP_SET_GLOBAL-25]
	_ = x[OP_GET_LOCAL-26]
	_ = x[OP_SET_LOCAL-27]
	_ = x[OP_POP-28]
	_ = x[OP_POPN-29]
	_ = x[OP_JUMP-30]
	_ = x[OP_JUMP_IF_FALSE-31]
	_ = x[OP_CALL-32]
	_ = x[OP_RETURN-33]
	_ = x[OP_CLOSURE-34]
	_ = x[OP_GET_UPVALUE-35]
	_ = x[OP_SET_UPVALUE-36]
	_ = x[OP_CLOSE_UPVALUE-37]
	_ = x[OP_CLASS-38]
	_ = x[OP_GET_PROPERTY-39]
	_ = x[OP_SET_PROPERTY-40]
	_ = x[OP_METHOD-41]
	_ = x[OP_INVOKE-42]
	_ = x[OP_INHERIT-43]
	_ = x[OP_SUPER-44]
	_ = x[OP_PRINT-45]
}

const _OpCode_name = "OP_CONSTANTOP_TRUEOP_FALSEOP_NILOP_CONSTANT_M1OP_CONSTANT_0OP_CONSTANT_1OP_CONSTANT_2OP_CONSTANT_3OP_CONSTANT_4OP_CONSTANT_5OP_NEGATEOP_NOTOP_ADDOP_SUBTRACTOP_MULTIPLYOP_DIVIDEOP_EQUALOP_NOT_EQUALOP_GREATEROP_LESSOP_GREATER_EQUALOP_LESS_EQUALOP_DEFINE_GLOBALOP_GET_GLOBALOP_SET_GLOBALOP_GET_LOCALOP_SET_LOCALOP_POPOP_POPNOP_JUMPOP_JUMP_IF_FALSEOP_CALLOP_RETURNOP_CLOSUREOP_GET_UPVALUEOP_SET_UPVALUEOP_CLOSE_UPVALUEOP_CLASSOP_GET_PROPERTYOP_SET_PROPERTYOP_METHODOP_INVOKEOP_INHERITOP_SUPEROP_PRINT"

var _OpCode_index = [...]uint16{0, 11, 18, 26, 32, 46, 59, 72, 85, 98, 111, 124, 133, 139, 145, 156, 167, 176, 184, 196, 206, 213, 229, 242, 258, 271, 284, 296, 308, 314, 321, 328, 344, 351, 360, 370, 384, 398, 414, 422, 437, 452, 461, 470, 480, 488, 496}

func (i OpCode) String() string {
	if i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
